### PR TITLE
Update build docs help in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by alexttx**
Signed-off-by: Alex Tomlinson <4172734+alexttx@users.noreply.github.com>

### CODE REVIEW

**Review by smoyergh — APPROVED** [review]

**Review by smoyergh — APPROVED** [review]
Text looks good.  One of the checks is failing.

**Comment by alexttx** [comment]
Interesting error from the "Docs" CI check.  Maybe there is a `docs` target buried in there that I wasn't seeing:
```
ERROR: Can't invoke target `docs`: ambiguous name.Add target type and/or path:
- ./docs/doxygen/output:custom
- ./docs/doxygen/docs:run
Error: Process completed with exit code 1.
```

**Comment by tristan957** [comment]
I will check this out and let you know. My memory is hazy on how this works.

**Comment by tristan957** [comment]
@alexttx, the `docs` target already exists. You probably just didn't have doxygen on your system so the target didn't get generated.

**Comment by alexttx** [comment]
I have doxygen installed, but I was using `ninja` instead of `meson compile`.
I'll revert the meson change, and keep the documentation change.

**Comment by tristan957** [comment]
Makes sense. The `docs` target is specific to `meson compile`. `ninja` uses other target names as you found out.

**Review by tristan957 — APPROVED** [review]

**Pull request merged**
