### PR TITLE
Add MIT license and REUSE compliance

### PR DESCRIPTION
**Pull request by tristan957**
Signed-off-by: Tristan Partin <tpartin@micron.com>

### CODE REVIEW

**Comment by tristan957** [comment]
I double checked my own work on copyright years. As far as 3rd party code (xoroshiro, crc32c, rbtree, hyperloglog), I could use a review. It seems like reuse isn't picking up these files for whatever reason. May have to open a bug with them.

**Comment by tristan957** [comment]
https://github.com/fsfe/reuse-tool/issues/664

**Review by smoyergh — APPROVED** [review]
Given 943 files changed I did the following: reviewed all new files, sampled updates to existing.  Regarding REUSE tool issue with third-party files, I wouldn't hold up this PR to get those fixed, we can deal with them later.

**Comment by alexttx** [comment]
- Use C++ style comments in the examples shown in `docs/unit-test-mocking.md`
- File `tests/functional/cli/storage/profile/home-dne.sh` has an errant escaped newline

Here's a histogram-like view of all SPDX entries:
```
          1 SPDX-FileCopyrightText: Copyright 2012 Alexander Hall <alexhall@google.com>
          1 SPDX-FileCopyrightText: Copyright 2012 Marc Nunkesser <marcnunkesser@google.com>
          1 SPDX-FileCopyrightText: Copyright 2012 Stefan Heule <stheule@ethz.ch>
        353 SPDX-FileCopyrightText: Copyright 2015 Micron Technology, Inc.
          1 SPDX-FileCopyrightText: Copyright 2016 David Blackman
          3 SPDX-FileCopyrightText: Copyright 2016 Micron Technology, Inc.
          1 SPDX-FileCopyrightText: Copyright 2016 Sebastiano Vigna <vigna@acm.org>
          2 SPDX-FileCopyrightText: Copyright 2017 Micron Technology, Inc.
          8 SPDX-FileCopyrightText: Copyright 2018 Micron Technology, Inc.
         54 SPDX-FileCopyrightText: Copyright 2020 Micron Technology, Inc.
        371 SPDX-FileCopyrightText: Copyright 2021 Micron Technology, Inc.
          1 SPDX-FileCopyrightText: Copyright 2021 Micron Technology, Inc.\
        140 SPDX-FileCopyrightText: Copyright 2022 Micron Technology, Inc.
          2 SPDX-FileCopyrightText: Copyright 2023 Micron Technology, Inc.
          3 SPDX-FileCopyrightText: Copyright YYYY Micron Technology, Inc.
          1 SPDX-License-Identifier: Apache-2.0 AND CC-BY-4.0
        935 SPDX-License-Identifier: Apache-2.0 OR MIT
          3 SPDX-License-Identifier: BSD-2-Clause */
          1 SPDX-License-Identifier: CC0-1.0
```

**Comment by tristan957** [comment]
> Use C++ style comments in the examples shown in docs/unit-test-mocking.md

Not following

**Comment by smoyergh** [comment]
@alexttx, great SPDK stats, thanks for generating.  @tristan957, note there are 3 files with "Copyright YYYY".

**Comment by tristan957** [comment]
Steve, those are just examples in the unit test mocking document.

**Comment by alexttx** [comment]
> > Use C++ style comments in the examples shown in docs/unit-test-mocking.md
> 
> Not following

My bad.  I was thinking we used C++ style comments for SPDX in our main source.

**Review by alexttx — APPROVED** [review]

**Comment by tristan957** [comment]
CI should be good to go now. REUSE issue has been fixed. Will merge when CI finishes successfully.

**Pull request merged**
