### PR TITLE
Rename hse_kvdb_txn to hse_txn

### PR DESCRIPTION
**Pull request by tristan957**
kvdb prefix feels unnecessary.

Signed-off-by: Tristan Partin <tpartin@micron.com>

### CODE REVIEW

**Comment by alexttx** [comment]
No more API changes.

**Comment by smoyergh** [comment]
This seems inconsistent with our naming scheme.  We have hse_kvs_put(), rather than hse_put(), because a put is associated with a specific kvs.  Similarly, we have hse_kvdb_txn_foo() because a txn is associated with a specific kvdb.  Even in a world where an app can open multiple kvdb (which we don't yet support), a txn will never span multiple kvdb.

I'm a fan of shorter function names, but then by that argument we could probably do a similar renaming for most of the functions in the API, which at this point I wouldn't support.

Is there more to the rationale than just making the name shorter?

**Comment by tristan957** [comment]
All I really want to do is rename `struct hse_kvdb_txn` to `struct hse_txn`, and then do the subsequent rename in hse-java and hse-python. I was torn on the function renaming and will happily revert them.

I am not understanding why we don't want any 3.0 changes. At the very least, removing the original cursor read API should be high up there. If the reason is to shield SQA from changes, then I have been advocating for a while that SQA should be moving all their tests into this repo so that all changes can happen at once.

My impression was that 3.0 changes weren't happening due to bandwidth, but I burned the weekend oil to pull this one out, and would happily do more to get all the 3.0 changes in.

**Comment by smoyergh** [comment]
There's nothing inherently wrong with any of those proposed changes.  But what is the stopping criteria?  I gaurantee everyone who touches the code will have ideas on how API elements could be improved, but then we would never get to a stable API.

I agree that over time we need to move as much of the SQA infrastructure as possible into this repo.  But that doesn't adress the more fundamental question: what is the stopping criteria for non-functional API changes?

**Comment by tristan957** [comment]
> what is the stopping criteria for non-functional API changes?

I was under the impression we (meaning the 5 of us who contribute regularly to HSE these days) were all in agreement our API has 2 issues.

1. Unnecessary prefixing (`struct hse_kvdb_txn` -> `struct hse_txn`, it isn't called a `struct hse_kvdb_kvs` for instance)
2. verb/noun API naming scheme (`hse_kvdb_txn_state_get()` -> `hse_kvdb_txn_get_state()`)

**Pull request closed without merging**
