### PR TITLE
Add the ShellCheck static analysis tool

### PR DESCRIPTION
**Pull request by tristan957**
ShellCheck is a static analyzer for shell files. Helps catch various
issues one may accidentally introduce and helps to make sure you write
portable scripts where possible.

Signed-off-by: Tristan Partin <tpartin@micron.com>

### CODE REVIEW

**Comment by tristan957** [comment]
FYI. I already tested --suite smoke and it is all good to go. Seems like no regressions at least from the smoke tests that are actually enabled. Would like to get this PR in to continue my CLI tests.

**Review by alexttx — CHANGES_REQUESTED** [review]
This looks like too much for 2.1.0.  We can't afford any hiccups if we want 2.1.0 out before holiday break.

**Comment by tristan957** [comment]
None of this has to do with libhse. The only thing that changed at all were the smoke tests and mock generation scripts. The build still works. All the tests still pass. Even the smoke tests which don't get tested in CI still pass, so I am confused what is keeping this from going in.

**Comment by alexttx** [comment]
Internal SQA may depend on some of these scripts.  And with this many changes, there's a higher risk of breaking their automation -- which is a hiccup in the release testing that I don't want to risk.

**Comment by tristan957** [comment]
But they wouldn't be calling the scripts directly. They would be going through Meson, and I have already confirmed the tests pass, and I already dealt with the fallout over shell quoting causing some tests to fail.

**Comment by alexttx** [comment]
I agree the risk is low for "meson test" and github CI.  But I am referring to internal SQA scripts which use HSE scripts and tools directly.

**Comment by alexttx** [comment]
If @bhaveshvasandani  approves, the we can take it.  As the SQA gatekeeper, it's his call.

**Review by bhaveshvasandani — APPROVED** [review]

**Review by alexttx — APPROVED** [review]

**Comment by bhaveshvasandani** [comment]
> If @bhaveshvasandani approves, the we can take it. As the SQA gatekeeper, it's his call.

I believe this Pr will have minimal impact to SQA, I think this will not delay the 2.1.0 release

**Pull request merged**
