### PR TITLE
Remove non-standard C99 integer types and constants

### PR DESCRIPTION
**Pull request by tristan957**
Signed-off-by: Tristan Partin <tpartin@micron.com>

### CODE REVIEW

**Comment by tristan957** [comment]
Worst PR of my life.

Could we __*please*__ get an auto formatter? Holy _expletive_!

**Comment by tristan957** [comment]
Just periodically rebasing so when the lucky day comes it is ready :)

**Comment by alexttx** [comment]
How about we commit to clang-format and then make this change?  Can we do it? Yes we can!

**Comment by beckerg** [comment]
Has clang-format improved not to make an effing mess of everything?

**Comment by tristan957** [comment]
To me, it has always been good enough, but obviously stuff gets better with every release of the clang stack. Just needs someone to do what Alex did before to update what we currently have, figure out any changes we might want, and re-evaluate the output.

**Review by beckerg — APPROVED** [review]

**Review by alexttx — APPROVED** [review]

**Pull request merged**
