### PR TITLE
ci: capture more logs

### PR DESCRIPTION
**Pull request by bhaveshvasandani**
Signed-off-by: bvasandani <bvasandani@micron.com>

### CODE REVIEW

**Review by nabeelmmd — APPROVED** [review]

**Comment by tristan957** [comment]
Yea I think adding `-v` is the way to go. Looks much better when peering at a glance.

**Review by tristan957 — APPROVED** [review]

**Comment by tristan957** [comment]
Hopefully we see a SIGSEGV here...

**Comment by nabeelmmd** [comment]
> Hopefully we see a SIGSEGV here...

That will be timely :-)

**Comment by nabeelmmd** [comment]
The mdc_test failure is because we are not reading back zeroes from the pre-allocated space after a posix_fallocate() call.

This failure is non-deterministic and is seen only on the github runners running ub18.04.

**Pull request merged**
