### PR TITLE
Fix recursive include issue

### PR DESCRIPTION
**Pull request by tristan957**
Signed-off-by: Tristan Partin <tpartin@micron.com>

## Description

Another case study in header files needing to include what they use.

## Verified checks?
Have the checks completed?
- [x] meson test -C build --setup=ci
- [x] All commits are signed off

### CODE REVIEW

**Review by beckerg — APPROVED** [review]

**Comment by beckerg** [comment]
Not recursive inclusivion, right?  More like piggyback inclusion.  I run across this quite a lot...

**Comment by tristan957** [comment]
No it was logging.h including event_counter.h which included logging.h which included....

**Comment by tristan957** [comment]
I agree on the piggyback inclusion. We really should take the philosophy of "include what you use". Our code is spaghetti when it comes what relationships exist between what files. I have plans to fix it, but it will have to be post 2.1 probably; although it'll make backporting fixes to 2.1 a hassle.

**Comment by beckerg** [comment]
Oh man, you should have seen it before I cleaned up it.  event_counter.h set a #define to prevent evaluation of stuff due to the recusive inclusion.  But I got rid of all that stuff so that only logging_types needed to be included which allowed you to further untangle this mess :-)  Same for gparams which now are only needed by logging.c, thanks for cleaning this stuff up!

**Review by nabeelmmd — APPROVED** [review]

**Pull request merged**
