### PR TITLE
Fix a few header dependencies

### PR DESCRIPTION
**Pull request by alexttx**
Signed-off-by: Alex Tomlinson <4172734+alexttx@users.noreply.github.com>

### CODE REVIEW

**Review by tristan957 — APPROVED** [review]

**Comment by tristan957** [comment]
Yay for GitHub mobile!

**Comment by alexttx** [comment]
The upcoming clang-format PR reorders include files.  Testing exposed a few dependency errors.  Fixing them now will make the reformat easier.

**Comment by tristan957** [comment]
Makes sense to me

**Review by gsramdasi — APPROVED** [review]

**Comment by beckerg** [comment]
Scary.  That's just the obvious ones you can detect...

**Pull request merged**
